alert("Ceci est une chaine de caractères : ");
let a = 100;
alert("Ceci est une chaine de caractères : " + a);
let b = a;
b--;
alert("Ceci est une chaine de caractères : " + b);
let c = a + 1.00;
alert("Ceci est une chaine de caractères : " + c);
let d = true;
alert("Ceci est une chaine de caractères : " + !d);